<?php

namespace PandoraBundle\Repository;

use PandoraBundle\Entity\Playerprofiles;
use Doctrine\ORM\EntityRepository;

/**
 * PlayerProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerProfileRepository extends EntityRepository
{

    /**
     * @return Playerprofiles[]
     */
    public function findAllOrdered()
    {
        return $this->createQueryBuilder('t')
            ->orderBy('t.datecreated', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function removeCompleted()
    {
        $this->createQueryBuilder('t')
             ->delete()
             ->where('t.completed = :true')
             ->setParameter('true', true)
             ->getQuery()
             ->execute();
    }
}
