<?php

namespace PandoraBundle\Repository;

use AppBundle\Entity\UserAccess;
use Doctrine\ORM\EntityRepository;

/**
 * UserAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAccessRepository extends EntityRepository
{
    /**
     * @return UserAccess[]
     */
    public function findAllOrdered()
    {
        return $this->createQueryBuilder('t')
            ->getQuery()
            ->getResult();
    }
    
    public function mutateUserAccess(array $arguments){
//         print_r($arguments);
//         exit;
    }
}
