<?php

namespace PandoraBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @return User[]
     */
    public function findAllOrdered()
    {
        return $this->createQueryBuilder('t')
            ->orderBy('t.datecreated', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function removeCompleted()
    {
        $this->createQueryBuilder('t')
             ->delete()
             ->where('t.completed = :true')
             ->setParameter('true', true)
             ->getQuery()
             ->execute();
    }
}
