pandora:
    resource: "@PandoraBundle/Resources/config/routing.php"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

api_login_check:
    path: /api/login_check

graphql:
    resource: '@GraphQLBundle/Controller/'

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /