<?php
/**
 * This class was automatically generated by GraphQL Schema generator
 */

namespace PandoraBundle\GraphQL;

use PandoraBundle\GraphQL\Mutation\MutationType;
use PandoraBundle\GraphQL\Query\QueryType;
use Youshido\GraphQL\Schema\AbstractSchema;
use Youshido\GraphQL\Config\Schema\SchemaConfig;

class Schema extends AbstractSchema
{
    public function build(SchemaConfig $config)
    {
        $config->setMutation(new MutationType())->setQuery(new QueryType());
    }
}